"""Add bio to users and missing models

Revision ID: 0895657b0ea3
Revises: feb11ea7fb63
Create Date: 2026-05-11 09:46:00.257328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0895657b0ea3'
down_revision: Union[str, Sequence[str], None] = 'feb11ea7fb63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enrollmentstatus enum type
    op.execute("CREATE TYPE enrollmentstatus AS ENUM ('ENROLLED', 'COMPLETED', 'DROPPED')")
    
    # Add INSTRUCTOR to userrole enum
    # Note: Using op.execute for Postgres compatibility
    op.execute("ALTER TYPE userrole ADD VALUE 'INSTRUCTOR'")

    op.create_table('course_prerequisites',
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('prerequisite_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['prerequisite_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('course_id', 'prerequisite_id')
    )
    op.create_table('waitlist_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waitlist_entries_id'), 'waitlist_entries', ['id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('enrollment_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enrollment_id')
    )
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.add_column('courses', sa.Column('category', sa.String(), nullable=True))
    op.add_column('courses', sa.Column('instructor_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'courses', 'users', ['instructor_id'], ['id'])
    op.add_column('enrollments', sa.Column('status', sa.Enum('ENROLLED', 'COMPLETED', 'DROPPED', name='enrollmentstatus'), nullable=False, server_default='ENROLLED'))
    op.add_column('enrollments', sa.Column('grade', sa.String(), nullable=True))
    op.add_column('users', sa.Column('bio', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    op.drop_column('enrollments', 'grade')
    op.drop_column('enrollments', 'status')
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'instructor_id')
    op.drop_column('courses', 'category')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_waitlist_entries_id'), table_name='waitlist_entries')
    op.drop_table('waitlist_entries')
    op.drop_table('course_prerequisites')
    
    # Drop enrollmentstatus enum type
    op.execute("DROP TYPE enrollmentstatus")
    # Note: We can't easily remove a value from an Enum in Postgres, 
    # so we leave 'userrole' as is for downgrade.
    # ### end Alembic commands ###
