"""add syllabus_url to course and resource_url to lesson

Revision ID: 9bd232d60c82
Revises: b97eee443bf1
Create Date: 2026-05-11 18:34:39.133214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bd232d60c82'
down_revision: Union[str, Sequence[str], None] = 'b97eee443bf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('syllabus_url', sa.String(), nullable=True))
    op.add_column('lessons', sa.Column('resource_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'resource_url')
    op.drop_column('courses', 'syllabus_url')
    # ### end Alembic commands ###
