"""add_description_to_courses

Revision ID: cbe345d2eb3b
Revises: 9bd232d60c82
Create Date: 2026-05-11 22:44:58.716195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbe345d2eb3b'
down_revision: Union[str, Sequence[str], None] = '9bd232d60c82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'description')
    # ### end Alembic commands ###
